export const RELAY_TRANSACT_PACKAGE_VERSION_V1 = 1;
export const RELAY_TRANSACT_SUPPORTED_SIGNAL_COUNT = 79;
export const RELAY_TRANSACT_FIELD_BYTES = 32;
export const RELAY_TRANSACT_SIGNAL_PREFIX_BYTES = 4;

export const RELAY_SIGNAL_INDEX_NULLIFIER_0 = 0;
export const RELAY_SIGNAL_INDEX_NULLIFIER_1 = 1;
export const RELAY_SIGNAL_INDEX_STATE_ROOT = 70;
export const RELAY_SIGNAL_INDEX_WITHDRAW_ADDRESS_HI = 71;
export const RELAY_SIGNAL_INDEX_WITHDRAW_ADDRESS_LO = 72;
export const RELAY_SIGNAL_INDEX_PUBLIC_WITHDRAWAL_ASSET_HI = 73;
export const RELAY_SIGNAL_INDEX_PUBLIC_WITHDRAWAL_ASSET_LO = 74;
export const RELAY_SIGNAL_INDEX_PUBLIC_DEPOSIT_ASSET_HI = 75;
export const RELAY_SIGNAL_INDEX_PUBLIC_DEPOSIT_ASSET_LO = 76;
export const RELAY_SIGNAL_INDEX_PUBLIC_DEPOSIT = 77;
export const RELAY_SIGNAL_INDEX_PUBLIC_WITHDRAWAL = 78;
