export const RELAY_TRANSACT_PACKAGE_VERSION_V1 = 1;
export const RELAY_TRANSACT_SUPPORTED_SIGNAL_COUNT = 93;
export const RELAY_TRANSACT_FIELD_BYTES = 32;
export const RELAY_TRANSACT_SIGNAL_PREFIX_BYTES = 4;

export const RELAY_SIGNAL_INDEX_NULLIFIER_0 = 0;
export const RELAY_SIGNAL_INDEX_NULLIFIER_1 = 1;
export const RELAY_SIGNAL_INDEX_STATE_ROOT = 82;
export const RELAY_SIGNAL_INDEX_WITHDRAW_ADDRESS_HI = 83;
export const RELAY_SIGNAL_INDEX_WITHDRAW_ADDRESS_LO = 84;
export const RELAY_SIGNAL_INDEX_ESCROW_RECIPIENT_HI = 85;
export const RELAY_SIGNAL_INDEX_ESCROW_RECIPIENT_LO = 86;
export const RELAY_SIGNAL_INDEX_PUBLIC_WITHDRAWAL_ASSET_HI = 87;
export const RELAY_SIGNAL_INDEX_PUBLIC_WITHDRAWAL_ASSET_LO = 88;
export const RELAY_SIGNAL_INDEX_PUBLIC_DEPOSIT_ASSET_HI = 89;
export const RELAY_SIGNAL_INDEX_PUBLIC_DEPOSIT_ASSET_LO = 90;
export const RELAY_SIGNAL_INDEX_PUBLIC_DEPOSIT = 91;
export const RELAY_SIGNAL_INDEX_PUBLIC_WITHDRAWAL = 92;
