export const STELLAR_STATE_PATHS = {
  privateRecords: '$.privateRecords',
  registryPrivateAddresses: '$.registry.privateAddresses',
  registryRegisteredAddresses: '$.registry.registeredAddresses',
  registryLookups: '$.registry.lookups',
  assets: '$.assets',
  assetsById: '$.assets.byId',
  assetsListOrder: '$.assets.listOrder',
  publicBalances: '$.balances.publicByOwnerAsset',
  poolsByContract: '$.pools.byContract',
  poolsLeafEphemeral: '$.pools.leafEphemeralByContractAndIndex',
  deliveriesIncomingById: '$.deliveries.incomingById',
  deliveriesSync: '$.deliveries.syncByPrivateAddressAsset',
  transactionsByHash: '$.transactions.byHash',
  walletPrivateAddressScalars: '$.wallet.privateAddressScalars',
  walletPrivateAddressRecords: '$.wallet.privateAddressRecords',
  walletDefaultPrivateAddressNonce: '$.wallet.defaultPrivateAddressNonce',
} as const;
